\temp\bevsuit4\convert "1.snowflake.offset.png" "1.snowflake.offset.jpg"
\temp\bevsuit4\convert "10.diamond.bunyip.png" "10.diamond.bunyip.jpg"
\temp\bevsuit4\convert "11.photon.photon.png" "11.photon.photon.jpg"
\temp\bevsuit4\convert "12.bundy.bundy.png" "12.bundy.bundy.jpg"
\temp\bevsuit4\convert "13.hammer.hammer.png" "13.hammer.hammer.jpg"
\temp\bevsuit4\convert "14.bipole.bipole.png" "14.bipole.bipole.jpg"
\temp\bevsuit4\convert "15.caterpillar.caterpillar.png" "15.caterpillar.caterpillar.jpg"
\temp\bevsuit4\convert "16.compressed accordian.box.png" "16.compressed accordian.box.jpg"
\temp\bevsuit4\convert "17.danish tee.murphy.png" "17.danish tee.murphy.jpg"
\temp\bevsuit4\convert "18.zircon.zircon.png" "18.zircon.zircon.jpg"
\temp\bevsuit4\convert "19.ritz.icepick.png" "19.ritz.icepick.jpg"
\temp\bevsuit4\convert "2.sidebody donut.side flake donut.png" "2.sidebody donut.side flake donut.jpg"
\temp\bevsuit4\convert "20.piver.viper.png" "20.piver.viper.jpg"
\temp\bevsuit4\convert "21.zigzag.marquis.png" "21.zigzag.marquis.jpg"
\temp\bevsuit4\convert "22.tee.chinese tee.png" "22.tee.chinese tee.jpg"
\temp\bevsuit4\convert "3.side flake opal.turf.png" "3.side flake opal.turf.jpg"
\temp\bevsuit4\convert "4.monopod.monopod.png" "4.monopod.monopod.jpg"
\temp\bevsuit4\convert "5.opal.opal.png" "5.opal.opal.jpg"
\temp\bevsuit4\convert "6.stardian.stardian.png" "6.stardian.stardian.jpg"
\temp\bevsuit4\convert "7.sidebuddies.sidebuddies.png" "7.sidebuddies.sidebuddies.jpg"
\temp\bevsuit4\convert "8.canadian tee.canadian tee.png" "8.canadian tee.canadian tee.jpg"
\temp\bevsuit4\convert "9.cat_accordian.cat_accordian.png" "9.cat_accordian.cat_accordian.jpg"
